name: Build and Publish Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Cache VCPKG
      uses: actions/cache@v3
      with:
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
        path: |
          build/x64-debug/vcpkg_installed
          build/x64-release/vcpkg_installed

    - name: Cache Externals
      uses: actions/cache@v3
      with:
        key: externals-${{ runner.os }}-${{ hashFiles('.gitmodules') }}
        path: |
          build/x64-debug/external
          build/x64-release/external

    - name: Configure CMake
      run: |
        cmake --preset x64-release

    - name: Build and Install ParallaxGen
      run: |
        cmake --build build/x64-release --target install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: parallaxgen-artifacts-${{ github.sha }}
        path: install/x64-release
