name: Build and Publish Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Cache VCPKG
      uses: actions/cache@v3
      with:
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
        path: |
          build/vcpkg_installed

    - name: Cache Externals
      uses: actions/cache@v3
      with:
        key: externals-${{ runner.os }}-${{ hashFiles('.gitmodules') }}
        path: |
          build/external

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DCMAKE_INSTALL_PREFIX="./install"

    - name: Build and Install ParallaxGen
      run: |
        cmake .. --build . --config Release --target install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: parallaxgen-artifacts-${{ github.sha }}
        path: ./install
